version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-factorio_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: ofsm/ofsm:latest
    restart: unless-stopped
    environment:
      - FACTORIO_VERSION=stable
      - RCON_PASS=${APP_PASSWORD}
    ports:
      - "34197:34197/udp"
    volumes:
      - ${APP_DATA_DIR}/data/fsm-data:/opt/fsm-data
      - ${APP_DATA_DIR}/data/saves:/opt/factorio/saves
      - ${APP_DATA_DIR}/data/mods:/opt/factorio/mods
      - ${APP_DATA_DIR}/data/config:/opt/factorio/config
      - ${APP_DATA_DIR}/data/mod_packs:/opt/fsm/mod_packs