version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-searxng_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: searxng/searxng:latest
    restart: unless-stopped
    environment:
      - INSTANCE_NAME=umbrel
      - BASE_URL=${APP_DOMAIN}:${APP_PORT}/
    volumes:
      - ${APP_DATA_DIR}/data:/etc/searxng