version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-scrypted_server_1
      APP_PORT: 10443
      PROXY_AUTH_ADD: "false"

  server:
    image: koush/scrypted:v0.142.6-noble-full
    restart: unless-stopped
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer 43282fb9-27e4-4d93-b3c5-6c333ae4671f
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    ports:
      - "10444:10444"
    volumes:
      - ${APP_DATA_DIR}/data:/server/volume
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=SET_THIS_TO_SOME_RANDOM_TEXT
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"
    ports:
      - "10444:8080"
    command: --interval 3600 --cleanup --scope scrypted
