version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-tianji_server_1
      APP_PORT: 12345
      PROXY_AUTH_ADD: "false"

  server:
    image: moonrailgun/tianji:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://tianji:tianji@postgres:5432/tianji
      - JWT_SECRET=${APP_PASSWORD}
      - ALLOW_REGISTER=false
      - ALLOW_OPENAPI=true
    depends_on:
      - postgres

  postgres:
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tianji
      - POSTGRES_USER=tianji
      - POSTGRES_PASSWORD=tianji
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5