version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-website-host_server_1
      APP_PORT: 12000

  server:
    image: php:8.2-apache
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12000"]
      interval: 30s
      timeout: 10s
      retries: 3

