version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-erugo_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: wardy784/erugo:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html/storage