version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-bookstack_bookstack_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  mysql:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:latest
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret
      - APP_URL=${APP_DOMAIN}:${APP_PORT}
      - APP_KEY=SomeRandomStringWith32Characters
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/var/www/bookstack/public/uploads
      - ${APP_DATA_DIR}/data/storage-uploads:/var/www/bookstack/storage/uploads
