version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-goaway_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: pommee/goaway:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW    
    
