version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: luna-mino-beszel_server_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"

  server:
    image: henrygd/beszel:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/beszel_data